spring:
  datasource:
    username: root
    password: 19971010,AN
    url: jdbc:mysql://localhost:3306/news_website?serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: an.easycodedemo.entity
